channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - accelerate
      - aiohappyeyeballs
      - aiohttp
      - aiosignal
      - aiosqlite
      - annotated-types
      - anyio
      - astor
      - async-timeout
      - attrs
      - backoff
      - banks
      - beautifulsoup4
      - blake3
      - cachetools
      - cbor2
      - certifi
      - cffi
      - charset-normalizer
      - click
      - cloudpickle
      - cmake
      - colorama
      - compressed-tensors
      - contourpy
      - cupy-cuda12x
      - cycler
      - dataclasses-json
      - datasets
      - defusedxml
      - deprecated
      - depyf
      - dill
      - dirtyjson
      - diskcache
      - distro
      - dnspython
      - einops
      - email-validator
      - exceptiongroup
      - faiss-cpu
      - fastapi
      - fastapi-cli
      - fastapi-cloud-cli
      - fastrlock
      - filelock
      - filetype
      - fonttools
      - frozenlist
      - fsspec
      - gguf
      - greenlet
      - griffe
      - h11
      - hf-xet
      - httpcore
      - httptools
      - httpx
      - huggingface-hub
      - idna
      - interegular
      - jieba
      - jinja2
      - jiter
      - joblib
      - jsonlines
      - jsonschema
      - jsonschema-specifications
      - kiwisolver
      - lark
      - llama-index
      - llguidance
      - llvmlite
      - lm-format-enforcer
      - markdown-it-py
      - markupsafe
      - marshmallow
      - matplotlib
      - mdurl
      - mistral-common
      - mpmath
      - msgpack
      - msgspec
      - multidict
      - multiprocess
      - mypy-extensions
      - nest-asyncio
      - networkx
      - ninja
      - nltk
      - numba
      - numpy
      - nvidia-cublas-cu12
      - nvidia-cuda-cupti-cu12
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - nvidia-cudnn-cu12
      - nvidia-cufft-cu12
      - nvidia-cufile-cu12
      - nvidia-curand-cu12
      - nvidia-cusolver-cu12
      - nvidia-cusparse-cu12
      - nvidia-cusparselt-cu12
      - nvidia-ml-py
      - nvidia-nccl-cu12
      - nvidia-nvjitlink-cu12
      - nvidia-nvtx-cu12
      - openai
      - openai-harmony
      - opencv-python-headless
      - outlines
      - packaging
      - pandas
      - partial-json-parser
      - pillow
      - platformdirs
      - prometheus-client
      - prometheus-fastapi-instrumentator
      - propcache
      - protobuf
      - psutil
      - py-cpuinfo
      - pyairports
      - pyarrow
      - pybase64
      - pycountry
      - pycparser
      - pydantic
      - pydantic-core
      - pydantic-extra-types
      - pygments
      - pyparsing
      - pypdf
      - python-dateutil
      - python-dotenv
      - python-json-logger
      - python-multipart
      - pytz
      - pyyaml
      - pyzmq
      - ray
      - referencing
      - regex
      - requests
      - rich
      - rich-toolkit
      - rignore
      - rpds-py
      - safetensors
      - scikit-learn
      - scipy
      - seaborn
      - sentence-transformers
      - sentencepiece
      - sentry-sdk
      - setproctitle
      - setuptools
      - shellingham
      - six
      - sniffio
      - soundfile
      - soupsieve
      - soxr
      - sqlalchemy
      - starlette
      - striprtf
      - sympy
      - tenacity
      - threadpoolctl
      - tiktoken
      - tokenizers
      - torch
      - torchaudio
      - torchvision
      - tqdm
      - transformers
      - triton
      - typer
      - typing-extensions
      - typing-inspect
      - typing-inspection
      - tzdata
      - urllib3
      - uvicorn
      - uvloop
      - vllm
      - vllm-flash-attn
      - watchfiles
      - websockets
      - wrapt
      - xformers
      - xgrammar
      - xxhash
      - yarl
