model:
  llama3.1-8b-instruct: "" # path to llama3.1-8b-instruct model
  bge-large-en-v1.5: "/gpuhome/sks6765/.cache/huggingface/hub/models--BAAI--bge-large-en-v1.5/snapshots/d4aa6901d3a41ba39fb536a557fa166f842b0e09" # path to bge-large-en-v1.5 model
  qwen2.5-7b-instruct: "/gpuhome/sks6765/.cache/huggingface/hub/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28" # path to qwen2.5-7b-instruct model
